services:
  agenda-contatos:
    image: ${DOCKER_REGISTRY-}agenda-contatos
    build:
      context: .
      dockerfile: .
    ports:
      - "5298:5298"
    depends_on:
      - sqldata
    
  front-vue:
    image: ${DOCKER_REGISTRY-}front-vue
    build:
      context: ..\..\front-vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=SqlDocker*2023
      - ACCEPT_EULA=Y
    volumes:
      - ../sqlserverdocker:var/opt/mssql/data
    ports:
      - "1433:1433"
  