services:
  agenda-contatos:
    image: ${DOCKER_REGISTRY-}agenda-contatos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5298:5298"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=SqlDocker*2023
      - ACCEPT_EULA=Y
    volumes:
      - c:/users/user1/desktop/agenda-contatos/sqlserverdocker:var/opt/mssql/data
    ports:
      - "1433:1433"
  