// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using agenda_contatos.DataAccess;

#nullable disable

namespace agenda_contatos.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231106214443_AddUsuarioTbl")]
    partial class AddUsuarioTbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("agenda_contatos.Models.Contato", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Contatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "machadodass__s@gmail.com",
                            Nome = "Joaquim Maria Machado de Assis",
                            Telefone = "81996542384"
                        },
                        new
                        {
                            Id = 2,
                            Email = "saramagoo22@outlook.com",
                            Nome = "José de Sousa Saramago",
                            Telefone = "83987785427"
                        },
                        new
                        {
                            Id = 3,
                            Email = "joaozindemelo@hotlink.com.br",
                            Nome = "João Cabral de Melo Neto",
                            Telefone = "81999578981"
                        });
                });

            modelBuilder.Entity("agenda_contatos.Models.Usuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "machadodass__s@gmail.com",
                            NomeDeUsuario = "Joaquim Maria Machado de Assis",
                            Role = "Admin",
                            Senha = "123456",
                            Telefone = "81984579681"
                        },
                        new
                        {
                            Id = 2,
                            Email = "saramago22@outlook.com",
                            NomeDeUsuario = "José de Sousa Saramago",
                            Role = "Usuario",
                            Senha = "123456",
                            Telefone = "83968495352"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
